#!/bin/bash
set -euo pipefail
if [[ "${S2T_PACKAGE_LOCK_HELD:-0}" != "1" ]]; then
    exec python3 - "$0" "$@" <<'PYLOCK'
import fcntl
import os
import pathlib
import subprocess
import sys

root = pathlib.Path(sys.argv[1]).resolve().parent.parent
(root / "build").mkdir(exist_ok=True)
with (root / "build/.package.lock").open("a") as lock:
    fcntl.flock(lock, fcntl.LOCK_EX)
    env = dict(os.environ, S2T_PACKAGE_LOCK_HELD="1")
    raise SystemExit(subprocess.call(["bash", str(root / "scripts/build-app.sh"), *sys.argv[2:]], env=env))
PYLOCK
fi
cd "$(dirname "$0")/.."
source scripts/toolchain.sh
S2T_FINAL_APP="$PWD/build/S2T.app"
S2T_STAGE_ROOT=$(mktemp -d "$PWD/build/.app-stage-XXXXXXXX")
APP="$S2T_STAGE_ROOT/S2T.app"
S2T_BACKUP="$S2T_STAGE_ROOT/previous.app"
cleanup() {
    local status=$?
    if [[ -e "$S2T_BACKUP" && ! -e "$S2T_FINAL_APP" ]]; then
        mv "$S2T_BACKUP" "$S2T_FINAL_APP" || true
    fi
    if [[ -e "$S2T_BACKUP" && ! -e "$S2T_FINAL_APP" ]]; then
        echo "Could not restore the previous app; preserving it at $S2T_BACKUP." >&2
    else
        case "$S2T_STAGE_ROOT" in "$PWD"/build/.app-stage-*) rm -rf "$S2T_STAGE_ROOT" ;; esac
    fi
    return "$status"
}
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM
S2T_PREVIOUS_BUILD=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$S2T_FINAL_APP/Contents/Info.plist" 2>/dev/null || echo 0)
if [[ ! "$S2T_PREVIOUS_BUILD" =~ ^[0-9]+$ ]]; then S2T_PREVIOUS_BUILD=0; fi
S2T_BUILD_NUMBER=$((S2T_PREVIOUS_BUILD + 1))
S2T_VERSION=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' Resources/Info.plist)
S2T_BUILD_DATE=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
cat > Sources/S2TApp/BuildIdentity.swift <<EOF
// Generated by scripts/build-app.sh. Compiled in so an old process cannot report a new bundle's version.
enum BuildIdentity {
    static let version = "$S2T_VERSION"
    static let number = "$S2T_BUILD_NUMBER"
    static let builtAt = "$S2T_BUILD_DATE"
    static let menuLabel = "S2T $S2T_VERSION · Build $S2T_BUILD_NUMBER"
}
EOF
swift build --disable-sandbox --build-system native --scratch-path .build/xcode -c release
S2T_BIN_DIR=$(swift build --disable-sandbox --build-system native --scratch-path .build/xcode -c release --show-bin-path)
if [[ "${S2T_UNIVERSAL:-0}" == "1" ]]; then
    S2T_OTHER_ARCH=x86_64
    if [[ "$(uname -m)" == "x86_64" ]]; then S2T_OTHER_ARCH=arm64; fi
    S2T_OTHER_TRIPLE="$S2T_OTHER_ARCH-apple-macosx14.0"
    swift build --disable-sandbox --build-system native --scratch-path .build/beta-cross -c release --triple "$S2T_OTHER_TRIPLE"
    S2T_OTHER_BIN_DIR=$(swift build --disable-sandbox --build-system native --scratch-path .build/beta-cross -c release --triple "$S2T_OTHER_TRIPLE" --show-bin-path)
fi
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
if [[ "${S2T_UNIVERSAL:-0}" == "1" ]]; then
    lipo -create "$S2T_BIN_DIR/S2T" "$S2T_OTHER_BIN_DIR/S2T" -output "$APP/Contents/MacOS/S2T.next"
else
    cp "$S2T_BIN_DIR/S2T" "$APP/Contents/MacOS/S2T.next"
fi
mv -f "$APP/Contents/MacOS/S2T.next" "$APP/Contents/MacOS/S2T"
if [ -d "$APP/Contents/Resources/Glur_Glur.bundle" ]; then
    chmod -R u+w "$APP/Contents/Resources/Glur_Glur.bundle"
fi
cp -R "$S2T_BIN_DIR/Glur_Glur.bundle" "$APP/Contents/Resources/"
if [ -d "$APP/Contents/Resources/S2T_S2TCore.bundle" ]; then
    chmod -R u+w "$APP/Contents/Resources/S2T_S2TCore.bundle"
fi
cp -R "$S2T_BIN_DIR/S2T_S2TCore.bundle" "$APP/Contents/Resources/"
mkdir -p "$APP/Contents/Resources/LocalModels"
cp Resources/LocalModels/catalog.json Resources/LocalModels/worker.py Resources/LocalModels/requirements.txt Resources/LocalModels/response_text.py "$APP/Contents/Resources/LocalModels/"
cp -R Resources/ThirdParty "$APP/Contents/Resources/"
cp -R Resources/Appearance "$APP/Contents/Resources/"
cp -R Resources/Typography "$APP/Contents/Resources/"
mkdir -p "$APP/Contents/Resources/Dashboard/fonts"
cp Resources/Dashboard/* "$APP/Contents/Resources/Dashboard/"
cp billing-local/public/s2t.svg "$APP/Contents/Resources/Dashboard/"
cp billing-local/public/fonts/* "$APP/Contents/Resources/Dashboard/fonts/"
sed "s|url('/fonts/|url('fonts/|g" billing-local/public/style.css > "$APP/Contents/Resources/Dashboard/website.css"
node scripts/build-policies.mjs --release --destination "$APP/Contents/Resources/policies"
S2T_EXISTING_CREDITS_URL=""
if [[ -f "$S2T_FINAL_APP/Contents/Info.plist" ]]; then
    S2T_EXISTING_CREDITS_URL=$(/usr/libexec/PlistBuddy -c 'Print :S2TCreditsURL' "$S2T_FINAL_APP/Contents/Info.plist" 2>/dev/null || true)
fi
cp Resources/Info.plist "$APP/Contents/Info.plist"
S2T_CREDITS_URL="${S2T_CREDITS_URL:-$S2T_EXISTING_CREDITS_URL}" python3 - "$APP/Contents/Info.plist" <<'PYCREDITS'
import os, plistlib, sys
from urllib.parse import urlsplit
address = os.environ.get("S2T_CREDITS_URL", "")
if address:
    url = urlsplit(address)
    if url.scheme != "https" or not url.hostname or url.username or url.password or url.path not in ("", "/") or url.query or url.fragment:
        raise SystemExit("S2T_CREDITS_URL must be a public HTTPS origin")
    with open(sys.argv[1], "rb") as source:
        metadata = plistlib.load(source)
    metadata["S2TCreditsURL"] = address.rstrip("/")
    with open(sys.argv[1], "wb") as target:
        plistlib.dump(metadata, target)
PYCREDITS
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $S2T_BUILD_NUMBER" "$APP/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Add :S2TBuildDateUTC string $S2T_BUILD_DATE" "$APP/Contents/Info.plist"
xcrun actool Resources/Assets.xcassets Logo/S2T.icon \
    --compile "$APP/Contents/Resources" --platform macosx \
    --minimum-deployment-target 14.0 --app-icon S2T \
    --output-partial-info-plist "$S2T_STAGE_ROOT/icon-info.plist"
python3 scripts/sanitize-app.py "$APP" "$PWD"
codesign --force --sign - --identifier com.s2t.dictation --requirements '=designated => identifier "com.s2t.dictation"' "$APP"
codesign --verify --deep --strict "$APP"
if [[ -e "$S2T_FINAL_APP" ]]; then mv "$S2T_FINAL_APP" "$S2T_BACKUP"; fi
if ! mv "$APP" "$S2T_FINAL_APP"; then
    if [[ -e "$S2T_BACKUP" ]]; then mv "$S2T_BACKUP" "$S2T_FINAL_APP"; fi
    exit 1
fi
rm -rf "$S2T_BACKUP"
echo "Built $S2T_FINAL_APP"
