#!/bin/bash
set -euo pipefail
if [[ "${S2T_PACKAGE_LOCK_HELD:-0}" != "1" ]]; then
    exec python3 - "$0" "$@" <<'PYLOCK'
import fcntl
import os
import pathlib
import subprocess
import sys

root = pathlib.Path(sys.argv[1]).resolve().parent.parent
(root / "build").mkdir(exist_ok=True)
with (root / "build/.package.lock").open("a") as lock:
    fcntl.flock(lock, fcntl.LOCK_EX)
    env = dict(os.environ, S2T_PACKAGE_LOCK_HELD="1")
    raise SystemExit(subprocess.call(["bash", str(root / "scripts/build-app.sh"), *sys.argv[2:]], env=env))
PYLOCK
fi
cd "$(dirname "$0")/.."
source scripts/toolchain.sh
APP="$(pwd)/build/S2T.app"
S2T_PREVIOUS_BUILD=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$APP/Contents/Info.plist" 2>/dev/null || echo 0)
if [[ ! "$S2T_PREVIOUS_BUILD" =~ ^[0-9]+$ ]]; then S2T_PREVIOUS_BUILD=0; fi
S2T_BUILD_NUMBER=$((S2T_PREVIOUS_BUILD + 1))
S2T_VERSION=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' Resources/Info.plist)
S2T_BUILD_DATE=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
cat > Sources/S2TApp/BuildIdentity.swift <<EOF
// Generated by scripts/build-app.sh. Compiled in so an old process cannot report a new bundle's version.
enum BuildIdentity {
    static let version = "$S2T_VERSION"
    static let number = "$S2T_BUILD_NUMBER"
    static let builtAt = "$S2T_BUILD_DATE"
    static let menuLabel = "S2T $S2T_VERSION · Build $S2T_BUILD_NUMBER"
}
EOF
swift build --scratch-path .build/xcode -c release
S2T_BIN_DIR=$(swift build --scratch-path .build/xcode -c release --show-bin-path)
if [[ "${S2T_UNIVERSAL:-0}" == "1" ]]; then
    S2T_OTHER_ARCH=x86_64
    if [[ "$(uname -m)" == "x86_64" ]]; then S2T_OTHER_ARCH=arm64; fi
    S2T_OTHER_TRIPLE="$S2T_OTHER_ARCH-apple-macosx14.0"
    swift build --scratch-path .build/beta-cross -c release --triple "$S2T_OTHER_TRIPLE"
    S2T_OTHER_BIN_DIR=$(swift build --scratch-path .build/beta-cross -c release --triple "$S2T_OTHER_TRIPLE" --show-bin-path)
fi
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
if [[ "${S2T_UNIVERSAL:-0}" == "1" ]]; then
    lipo -create "$S2T_BIN_DIR/S2T" "$S2T_OTHER_BIN_DIR/S2T" -output "$APP/Contents/MacOS/S2T.next"
else
    cp "$S2T_BIN_DIR/S2T" "$APP/Contents/MacOS/S2T.next"
fi
mv -f "$APP/Contents/MacOS/S2T.next" "$APP/Contents/MacOS/S2T"
if [ -d "$APP/Contents/Resources/Glur_Glur.bundle" ]; then
    chmod -R u+w "$APP/Contents/Resources/Glur_Glur.bundle"
fi
cp -R "$S2T_BIN_DIR/Glur_Glur.bundle" "$APP/Contents/Resources/"
if [ -d "$APP/Contents/Resources/S2T_S2TCore.bundle" ]; then
    chmod -R u+w "$APP/Contents/Resources/S2T_S2TCore.bundle"
fi
cp -R "$S2T_BIN_DIR/S2T_S2TCore.bundle" "$APP/Contents/Resources/"
cp -R Resources/ThirdParty "$APP/Contents/Resources/"
cp -R Resources/Appearance "$APP/Contents/Resources/"
cp Resources/Info.plist "$APP/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $S2T_BUILD_NUMBER" "$APP/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Add :S2TBuildDateUTC string $S2T_BUILD_DATE" "$APP/Contents/Info.plist"
cp "Logo/Logo black fill.svg" Resources/Assets.xcassets/MenuBar.imageset/black.svg
cp "Logo/Logo white fill.svg" Resources/Assets.xcassets/MenuBar.imageset/white.svg
xcrun actool Resources/Assets.xcassets Logo/S2T.icon \
    --compile "$APP/Contents/Resources" --platform macosx \
    --minimum-deployment-target 14.0 --app-icon S2T \
    --output-partial-info-plist build/icon-info.plist
python3 scripts/sanitize-app.py "$APP" "$PWD"
codesign --force --sign - --identifier com.s2t.dictation --requirements '=designated => identifier "com.s2t.dictation"' "$APP"
codesign --verify --deep --strict "$APP"
echo "Built $APP"
