// Generated by scripts/build-app.sh. Compiled in so an old process cannot report a new bundle's version.
enum BuildIdentity {
    static let version = "1.0.1"
    static let number = "296"
    static let builtAt = "2026-09-14T19:36:08Z"
    static let menuLabel = "S2T 1.0.1 · Build 296"
}
